"use client";

import "./global.css";
import Page from "./page";
import MainContext from "@/context/Context";
import { useState, useEffect } from "react";

const metadata = {
  title: "Librouse",
  description: "Generated by Next.JS",
};

export default function RootLayout({ children }) {
  const [arr, setArr] = useState(0);
  const [data, setData] = useState();
  const [langArr, setLangArr] = useState(0);
  const [click, setClick] = useState(null);

  useEffect(() => {
    localStorage.setItem("lang", langArr);
  }, [langArr]);

  useEffect(() => {
    localStorage.setItem("theme", arr);
  }, [arr]);

  useEffect(() => {
    fetch("data.json")
      .then((res) => res.json())

      .then((data) => {
        setData(data);
      })
      .catch((error) => {
        console.error("API Error:", error);
      });
  }, []);

  return (
    <html lang="en" className={`scroll-${arr}`}>
      <head>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title>
      </head>
      <body>
        <MainContext.Provider
          value={{
            data,
            setData,
            arr,
            setArr,
            click,
            setClick,
            langArr,
            setLangArr,
          }}
        >
          <Page />
        </MainContext.Provider>
      </body>
    </html>
  );
}
