import "./main.sass";
import "animate.css";
import { Inter } from "next/font/google";
import Context from "./context/Context.jsx";
import Page from "./page";
import { Margin } from "@mui/icons-material";

export const metadata = {
  title: "Librouse",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title>
        <script src="https://cdn.tailwindcss.com"></script>
      </head>
      <body
        
      >
        <Page />
      </body>
    </html>
  );
}
